audit_header: false
title: LA Real Estate Video Blog with Victoria Velazquez
description: Our mission at Amalfi Estates is to be your best resource for Los Angeles real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Amalfi Estates, your professional Los Angeles Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: VICTORIA VELAZQUEZ
  title:
  license_number:
  about_markdown: |
    Can you imagine a world where sales people only want you to buy something if it is a wise decision? What if a car salesperson talked you out of buying a car because she or he thought you were overpaying? Amalfi Estates, one of Los Angeles’ leading independent real estate companies, might be that company. You see, Amalfi Estates is a bit different than other real estate firms.


    Operating as a team rather than individual agents allows us to provide a concierge level of service to our clients. Having Sales Partner specialists who live and breathe our culture of extraordinary performance while always keeping their client’s best interests at heart is what sets us apart.
  brand: 
  brokerage:
  market: LA
  address: '984 Monument St #105, Pacific Palisades, CA 90272'
  phone: 310-614-4240
  phone_type:
  phone2:
  phone2_type:
  email: victoria@amalfiestates.com
  url: 

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your LA Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a LA Home?"
    CTA_text2: "Search the entire MLS for your LA home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Victoria-Velazquez-Real-Estate-2294518010661924/
  linkedin_url:
  youtube_url:
  twitter_url: https://twitter.com/amalfiestates
  instagram_url: https://www.instagram.com/amalfiestates/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Los Angeles Real Estate Podcast with Victoria Velazquez'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Los Angeles Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Amalfi Estates - your professional Los Angeles Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Los Angeles, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Victoria Velazquez'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Los Angeles Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#04558A'
  theme_color: '#262F36'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
